name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./fake-twitter-frontend

      - name: Build Angular frontend
        run: npm run build -- --output-path=dist/browser
        working-directory: ./fake-twitter-frontend

      - name: Install CDK dependencies
        run: npm install
        working-directory: ./cdk

      - name: Bootstrap CDK
        run: cdk bootstrap aws://916661254529/us-east-1
        working-directory: ./cdk

      - name: Deploy with CDK
        run: cdk deploy --require-approval never --verbose
        working-directory: ./cdk
